#!/bin/bash
set -x

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_141
export PATH=$JAVA_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR
nohup java -Xms384m -Xmx412m -jar target/*.jar --spring.datasource.username=${OPENSHIFT_POSTGRESQL_DB_USERNAME} --spring.datasource.password=${OPENSHIFT_POSTGRESQL_DB_PASSWORD} --spring.datasource.url=jdbc:postgresql://${OPENSHIFT_POSTGRESQL_DB_HOST}:${OPENSHIFT_POSTGRESQL_DB_PORT}/${PGDATABASE} --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} 2> stderr.log 1> stdout.log &
