spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/test}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:testuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

server.port=${PORT:8080}
server.forward-headers-strategy=framework
spring.data.rest.base-path=api

spring.config.import=optional:configtree:/run/secrets/

# Auth0
auth0.domain=${AUTH0_DOMAIN:}
auth0.client-id=${AUTH0_CLIENT_ID:${auth0_client_id}}
spring.security.oauth2.client.registration.auth0.client-id=${auth0.client-id}
spring.security.oauth2.client.registration.auth0.client-secret=${AUTH0_CLIENT_SECRET:${auth0_client_secret}}
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email
spring.security.oauth2.client.registration.auth0.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.auth0.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.auth0.authorization-uri=${auth0.domain}/authorize
spring.security.oauth2.client.provider.auth0.token-uri=${auth0.domain}/oauth/token
spring.security.oauth2.client.provider.auth0.jwk-set-uri=${auth0.domain}/.well-known/jwks.json
spring.security.oauth2.client.provider.auth0.user-info-uri=${auth0.domain}/userinfo
spring.security.oauth2.client.provider.auth0.user-name-attribute=sub
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${auth0.domain}/.well-known/jwks.json
