name: Release on demand

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
#      - name: Set up JDK
#        uses: actions/setup-java@v1
#        with:
#          java-version: 15
#      - name: Build with Maven
#        run: mvn -B clean package --file backend/pom.xml
      - name: Run build script
        env:
         HEROKU_REGISTRY_PASSWORD: ${{ secrets.HEROKU_REGISTRY_PASSWORD }}
         HEROKU_REGISTRY_USERNAME: ${{ secrets.HEROKU_REGISTRY_USERNAME }}
        run: ./.github/scripts/deploy-to-heroku.sh
        shell: bash