name: tech-resource-tracker-release
on:
  schedule:
    - cron: '10 22 * * *'
  push:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '25'
      - name: Dump secrets into file
        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWD }}
          OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
          OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
        run: |
         echo "$CYPRESS_USERNAME" > auth0_username.txt
         echo "$CYPRESS_PASSWORD" > auth0_password.txt
         echo "$OKTA_CLIENT_ID" > auth0_client_id.txt
         echo "$OKTA_CLIENT_SECRET" > auth0_client_secret.txt
      - name: Build with Maven
        run: mvn -B clean verify -Pcompose --file backend/pom.xml
      - name: Archive Cypress artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: archive-cypress-video
          path: |
            /home/runner/work/tech-resource-tracker/tech-resource-tracker/frontend/src/main/frontend/cypress/screenshots/smoke.cy.ts
            /home/runner/work/tech-resource-tracker/tech-resource-tracker/frontend/src/main/frontend/cypress/screenshots/crud.cy.ts
          retention-days: 5
